clustermesh: use Cilium version extracted from helm secret if available
[ cherry-picked from cilium/cilium-cli repository ]

This fixes the following error in the external workload workflow in
cilium/cilium CI:

    Error: Unable to create external workload install script: No Major.Minor.Patch elements found

See https://github.com/cilium/cilium/pull/22441#issuecomment-1332086537

For https://github.com/cilium/cilium/issues/22451
Fixes: dcfb77269f48 ("clustermesh: Fix --bpf-lb-sock on < 1.12")

Signed-off-by: Tobias Klauser <tobias@cilium.io>