.github/workflows: use eksctl 0.54.0
[ cherry-picked from cilium/cilium-cli repository ]

The EKS workflows suddenly started failing with:

  Error: couldn't create node group filter from command line options: --spot is only valid with managed nodegroups (--managed)

On Jul 2 at around 15 CEST
(https://github.com/cilium/cilium-cli/actions/runs/992727965). The
release of eksctl 0.55.0 coincides with this time frame. As we pin the
EKS workflows to the latest eksctl release, it is likely that this
caused the failures.

Pin the eksctl to 0.54.0 for now which doesn't seem to exhibit this
behavior.

Ref: https://github.com/weaveworks/eksctl/issues/3929
Signed-off-by: Tobias Klauser <tobias@cilium.io>